## Exercises
___

**1.**

Create a tensor for _list(range(9))_. Predict and then check the size, offset and stride

In [6]:
import torch

a = torch.tensor(list(range(9)))
print("a size:", a.size())               # torch.Size([9])
print("a offset:", a.storage_offset())   # 0
print("a stride:", a.stride())           # (1,)

a size: torch.Size([9])
a offset: 0
a stride: (1,)


**1.a**

Create a new tensor using _b = a.view(3, 3)_. What does _view_ do? Check that _a_ and _b_ share the same storage

In [7]:
b = a.view(3, 3)  # creates a view from the same storage
print(a.storage())
print(b.storage())
print("b size:", b.size())              # torch.Size([3, 3])
print("b offset:", b.storage_offset())  # 0
print("b stride:", b.stride())          # (3, 1)

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]
 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]
b size: torch.Size([3, 3])
b offset: 0
b stride: (3, 1)


**1.b**

Create a tensor _c = b\[1:,1:\]_. Predict and then check the size, offset and stride

In [8]:
c = b[1:, 1:]
print("c size:", c.size())              # torch.Size([2, 2])
print("c offset:", c.storage_offset())  # 4
print("c stride:", c.stride())          # (3, 1)

c size: torch.Size([2, 2])
c offset: 4
c stride: (3, 1)


___
**2**

Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the _torch_library?

In [ ]:
# torch.sqrt(t)
# torch.sin(t)

**a**

Apply the function element-wise to _a_. Why does it return an error?

In [23]:
# torch.sqrt(a) # a must be a tensor of floating point values

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

**b**

What operation is required to make the function work?

In [27]:
#torch.sqrt(a.float())
torch.sqrt(a.to(dtype=float))

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)

**c**

Is there a version of your function that operates in place?

In [33]:
b = a.float()
print(b)
b.sqrt_()  # in-place operation
print(b)
b = a.float()
print(b)
torch.Tensor.sin_(b)  # in-place operation
print(b)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])
