## PyTorch tensors
___

**Tensors** are the fundamental data structure in PyTorch. A tensor is an array, that is, a data structure tht stores a collection of numbers that are accesible individually using an index

### Constructing tensors

In [5]:
import torch
a = torch.ones(3)
print(a)
print(a[1])
a[2] = 2.
print(a)

tensor([1., 1., 1.])
tensor(1.)
tensor([1., 1., 2.])


Python lists or tuples are collections of Python objects that are individually allocated in memory. PyTorch (or NumPy) tensors, on the oder hand, are contiguous memory blocks containing _unboxed_ C numeric types rather than Python objects.

In [28]:
points = torch.tensor([4.0, 1.0, 3.0, -1.0, 0.0, 2.0])
print(points)
print(type(points))
print(points.dtype)
print(points)
print(points.shape)
print(points[0])

tensor([ 4.,  1.,  3., -1.,  0.,  2.])
<class 'torch.Tensor'>
torch.float32
tensor([ 4.,  1.,  3., -1.,  0.,  2.])
torch.Size([6])
tensor(4.)


In [30]:
points = torch.tensor([[4.0, 1.0], [3.0, -1.0], [0.0, 2.0]])
print(pointsi)
print(type(pointsi))
print(pointsi.dtype)
print(points)
print(points.shape)
print(points[0])

tensor([ 4,  1,  3, -1], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
tensor([[ 4.,  1.],
        [ 3., -1.],
        [ 0.,  2.]])
torch.Size([3, 2])
tensor([4., 1.])


### Indexing tensors

In [39]:
print(points)
print(points[1:]) # all rows after the first; implicitly all columns
print(points[1:, :]) # all rows after the first; all columns
print(points[1:, 0]) # all rows after the first; first column

tensor([[ 4.,  1.],
        [ 3., -1.],
        [ 0.,  2.]])
tensor([[ 3., -1.],
        [ 0.,  2.]])
tensor([[ 3., -1.],
        [ 0.,  2.]])
tensor([3., 0.])


### Named tensors
As data is transformed through multiple tensors, keeping track of whch dimension contains what data can be error-prone

In [42]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
print("img_t:\n", img_t)

weights = torch.tensor([0.2126, 0.7152, 0.0722])
print("weights:\n", weights)

img_t:
 tensor([[[ 5.9593e-01, -2.2554e-01,  1.3033e+00,  4.3092e-01, -1.1777e-02],
         [ 8.8068e-01,  1.6422e-02, -1.3252e-01, -6.3991e-01,  2.4052e-01],
         [-1.1630e+00,  9.7681e-02,  1.3905e+00, -3.4770e-01,  2.4636e-01],
         [ 1.5399e-01,  1.2837e+00, -3.7645e-01, -9.6737e-02,  6.8970e-01],
         [ 1.0004e-03, -1.0694e+00, -3.7071e-01, -4.7061e-01,  6.0313e-01]],

        [[-7.3865e-01, -6.0208e-01, -6.4794e-01, -3.4129e-01, -5.4593e-01],
         [ 4.7147e-02,  3.0631e-01, -2.8535e-02, -2.3648e+00, -1.2492e+00],
         [ 2.5260e-01,  1.3576e+00,  2.2554e+00,  1.2114e+00, -1.5182e+00],
         [-1.2190e+00, -1.3453e+00,  2.6575e+00, -5.4048e-01,  5.1252e-01],
         [ 1.4009e+00, -8.7529e-01,  1.5244e-01, -2.9810e-01,  1.1409e+00]],

        [[ 1.4830e+00, -6.1663e-01,  9.3938e-02, -1.0401e+00, -1.3305e+00],
         [ 3.1038e-02, -1.4777e+00, -1.1980e+00, -1.4419e+00,  1.0255e+00],
         [ 4.6934e-01, -4.5564e-01, -1.4515e+00, -1.7802e+00,  1.6938e-01],


In [45]:
# multiple images
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
print("img_t:\n", batch_t)

img_t:
 tensor([[[[-1.4247e+00,  1.1949e+00, -4.2283e-01, -5.4617e-01, -1.1286e+00],
          [ 8.6600e-01, -1.0298e-01, -1.4553e+00, -4.5132e-01, -3.2064e-01],
          [ 2.7672e+00, -1.8659e+00, -7.2636e-01, -1.0149e+00, -1.2483e-01],
          [-1.8447e+00, -6.8048e-01,  9.1462e-01, -1.9755e+00, -1.1569e+00],
          [-7.0247e-01,  4.6351e-01,  1.5625e+00, -7.5395e-01, -8.2287e-01]],

         [[ 1.0138e+00, -1.2193e+00,  4.0404e-01, -1.1294e+00,  1.0647e+00],
          [-1.1283e+00,  6.5247e-01,  1.0382e+00, -2.0373e+00, -1.3780e-01],
          [ 3.0119e-01, -5.1570e-01, -9.5104e-01,  5.8515e-01, -1.8407e+00],
          [-9.5803e-01, -1.1343e-01,  9.0483e-01,  9.4589e-01,  1.4644e-01],
          [ 4.4431e-01, -1.3358e-02,  1.1697e+00, -2.4152e+00, -8.1803e-01]],

         [[-1.0996e+00,  3.0452e+00,  1.5221e+00, -1.7188e-01,  5.8116e-01],
          [-7.1621e-01,  1.5814e+00,  6.0045e-01, -1.7724e+00,  2.4083e+00],
          [-7.7640e-01, -4.4629e-01,  9.4052e-01, -1.2211e+00, -

As we saw, the RGB channels are in dimension 0 in the first case and in dimension 1 in the second. We could obtain the unweighted mean using dimension -3

In [46]:
img_gray_naive = img_t.mean(-3)
batch_t_naive = batch_t.mean(-3)
print(img_gray_naive, img_gray_naive.shape)
print(batch_t_naive, batch_t_naive.shape)

tensor([[ 0.4468, -0.4814,  0.2498, -0.3168, -0.6294],
        [ 0.3196, -0.3850, -0.4530, -1.4822,  0.0056],
        [-0.1470,  0.3332,  0.7314, -0.3055, -0.3675],
        [-0.3054,  0.1112,  0.4628, -0.8415, -0.0421],
        [ 0.3982, -0.5914,  0.3406, -0.4121,  0.0465]]) torch.Size([5, 5])
tensor([[[-0.5035,  1.0069,  0.5011, -0.6158,  0.1724],
         [-0.3262,  0.7103,  0.0611, -1.4203,  0.6500],
         [ 0.7640, -0.9426, -0.2456, -0.5503, -0.6841],
         [-1.0146,  0.0651,  1.0837,  0.0064,  0.0328],
         [-0.2581,  0.3297,  0.8598, -1.1232, -0.3865]],

        [[-0.1491,  1.0817,  0.5090,  0.4253,  0.4152],
         [ 1.4867,  0.0488, -0.1379, -0.0279, -0.6121],
         [-0.8663,  0.5203, -0.3150, -0.0287, -0.3151],
         [ 0.0915, -0.1459,  0.3424, -0.6641, -0.2200],
         [-0.2522,  0.5471, -0.5798,  0.4099,  0.1832]]]) torch.Size([2, 5, 5])


Working whith numeric indexes for dimensions can be messy... Better, use names. We can add names to an existing tensor using the method _refine_\__names_

In [53]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'batch_id', 'channels', 'rows', 'columns')
weights_named = weights.refine_names(..., 'channels')
print("img_named:", img_named.shape, img_named.names)
print("batch_named:", batch_named.shape, batch_named.names)
print("weights_named:", weights_named.shape, weights_named.names)

img_named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) ('batch_id', 'channels', 'rows', 'columns')
weights_named: torch.Size([3]) ('channels',)


In [56]:
weights_aligned = weights_named.align_as(img_named)
print("weights_aligned:", weights_aligned.shape, weights_aligned.names)

weights_aligned: torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')


Functions accepting dimension arguments also take named dimensions:

In [59]:
gray_named = (img_named * weights_aligned).sum('channels')
print(gray_named.shape, gray_named.names)

torch.Size([5, 5]) ('rows', 'columns')


If we want to use tensors outside functions that operate on named tensors, we need to drop the names by renaming them to _None_

In [60]:
gray_plain = gray_named.rename(None)
print("gray_plain:", gray_plain.shape, gray_plain.names)

gray_plain: torch.Size([5, 5]) (None, None)
