## PyTorch tensors
___

**Tensors** are the fundamental data structure in PyTorch. A tensor is an array, that is, a data structure that stores a collection of numbers that are accesible individually using an index

### Constructing tensors

In [2]:
import torch
a = torch.ones(3)
print(a)
print(a[1])
a[2] = 2.
print(a)

tensor([1., 1., 1.])
tensor(1.)
tensor([1., 1., 2.])


Python lists or tuples are collections of Python objects that are individually allocated in memory. PyTorch (or NumPy) tensors, on the oder hand, are contiguous memory blocks containing _unboxed_ C numeric types rather than Python objects.

In [2]:
points = torch.tensor([4.0, 1.0, 3.0, -1.0, 0.0, 2.0])
print(points)
print(type(points))
print(points.dtype)
print(points.shape)

tensor([ 4.,  1.,  3., -1.,  0.,  2.])
<class 'torch.Tensor'>
torch.float32
torch.Size([6])


In [4]:
points = torch.tensor([[4.0, 1.0], [3.0, -1.0], [0.0, 2.0]])
print(points)
print(type(points))
print(points.dtype)
print(points.shape)
print(points[0])

tensor([[ 4.,  1.],
        [ 3., -1.],
        [ 0.,  2.]])
<class 'torch.Tensor'>
torch.float32
torch.Size([3, 2])
tensor([4., 1.])


### Indexing tensors

In [5]:
print(points)
print(points[1:]) # all rows after the first; implicitly all columns
print(points[1:, :]) # all rows after the first; all columns
print(points[1:, 0]) # all rows after the first; first column

tensor([[ 4.,  1.],
        [ 3., -1.],
        [ 0.,  2.]])
tensor([[ 3., -1.],
        [ 0.,  2.]])
tensor([[ 3., -1.],
        [ 0.,  2.]])
tensor([3., 0.])


### Named tensors
As data is transformed through multiple tensors, keeping track of which dimension contains what data can be error-prone

In [6]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
print("img_t:\n", img_t)

weights = torch.tensor([0.2126, 0.7152, 0.0722])
print("weights:\n", weights)

img_t:
 tensor([[[-0.0258, -1.2125,  0.8376, -0.6120,  2.0765],
         [ 0.2579,  1.1854, -1.5875, -0.3985, -1.0811],
         [-1.2242,  1.7786, -1.3966,  0.8025,  1.2879],
         [ 0.3271, -0.6721,  0.0880, -0.6468,  0.5000],
         [-0.9931, -0.3810,  1.5752,  0.4030, -0.9618]],

        [[ 0.4382,  0.9779, -1.3235,  0.0557, -0.0860],
         [-0.9753,  1.3039,  1.4092, -1.3280,  0.5435],
         [ 0.2879,  0.5714,  0.4650, -0.2193, -1.3085],
         [-0.9611, -0.2746,  1.3587, -0.2521, -0.1916],
         [ 0.8649,  0.8873,  0.5976, -0.4790, -0.2231]],

        [[ 0.2584, -0.9934, -1.0889, -1.2935,  0.0070],
         [ 0.3049, -0.7106,  0.0565, -0.2007,  1.0209],
         [ 0.3737,  2.0778,  1.2476, -0.7243,  1.1933],
         [-1.3843,  0.9369,  1.5409,  0.6231,  0.6172],
         [ 1.4078, -0.4786,  0.1354,  0.1659, -0.1126]]])
weights:
 tensor([0.2126, 0.7152, 0.0722])


In [45]:
# multiple images
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
print("img_t:\n", batch_t)

img_t:
 tensor([[[[-1.4247e+00,  1.1949e+00, -4.2283e-01, -5.4617e-01, -1.1286e+00],
          [ 8.6600e-01, -1.0298e-01, -1.4553e+00, -4.5132e-01, -3.2064e-01],
          [ 2.7672e+00, -1.8659e+00, -7.2636e-01, -1.0149e+00, -1.2483e-01],
          [-1.8447e+00, -6.8048e-01,  9.1462e-01, -1.9755e+00, -1.1569e+00],
          [-7.0247e-01,  4.6351e-01,  1.5625e+00, -7.5395e-01, -8.2287e-01]],

         [[ 1.0138e+00, -1.2193e+00,  4.0404e-01, -1.1294e+00,  1.0647e+00],
          [-1.1283e+00,  6.5247e-01,  1.0382e+00, -2.0373e+00, -1.3780e-01],
          [ 3.0119e-01, -5.1570e-01, -9.5104e-01,  5.8515e-01, -1.8407e+00],
          [-9.5803e-01, -1.1343e-01,  9.0483e-01,  9.4589e-01,  1.4644e-01],
          [ 4.4431e-01, -1.3358e-02,  1.1697e+00, -2.4152e+00, -8.1803e-01]],

         [[-1.0996e+00,  3.0452e+00,  1.5221e+00, -1.7188e-01,  5.8116e-01],
          [-7.1621e-01,  1.5814e+00,  6.0045e-01, -1.7724e+00,  2.4083e+00],
          [-7.7640e-01, -4.4629e-01,  9.4052e-01, -1.2211e+00, -

As we saw, the RGB channels are in dimension 0 in the first case and in dimension 1 in the second. We could obtain the unweighted mean using dimension -3

In [46]:
img_gray_naive = img_t.mean(-3)
batch_t_naive = batch_t.mean(-3)
print(img_gray_naive, img_gray_naive.shape)
print(batch_t_naive, batch_t_naive.shape)

tensor([[ 0.4468, -0.4814,  0.2498, -0.3168, -0.6294],
        [ 0.3196, -0.3850, -0.4530, -1.4822,  0.0056],
        [-0.1470,  0.3332,  0.7314, -0.3055, -0.3675],
        [-0.3054,  0.1112,  0.4628, -0.8415, -0.0421],
        [ 0.3982, -0.5914,  0.3406, -0.4121,  0.0465]]) torch.Size([5, 5])
tensor([[[-0.5035,  1.0069,  0.5011, -0.6158,  0.1724],
         [-0.3262,  0.7103,  0.0611, -1.4203,  0.6500],
         [ 0.7640, -0.9426, -0.2456, -0.5503, -0.6841],
         [-1.0146,  0.0651,  1.0837,  0.0064,  0.0328],
         [-0.2581,  0.3297,  0.8598, -1.1232, -0.3865]],

        [[-0.1491,  1.0817,  0.5090,  0.4253,  0.4152],
         [ 1.4867,  0.0488, -0.1379, -0.0279, -0.6121],
         [-0.8663,  0.5203, -0.3150, -0.0287, -0.3151],
         [ 0.0915, -0.1459,  0.3424, -0.6641, -0.2200],
         [-0.2522,  0.5471, -0.5798,  0.4099,  0.1832]]]) torch.Size([2, 5, 5])


Working whith numeric indexes for dimensions can be messy... Better, use names. We can add names to an existing tensor using the method _refine_\__names_

In [53]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'batch_id', 'channels', 'rows', 'columns')
weights_named = weights.refine_names(..., 'channels')
print("img_named:", img_named.shape, img_named.names)
print("batch_named:", batch_named.shape, batch_named.names)
print("weights_named:", weights_named.shape, weights_named.names)

img_named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) ('batch_id', 'channels', 'rows', 'columns')
weights_named: torch.Size([3]) ('channels',)


In [56]:
weights_aligned = weights_named.align_as(img_named)
print("weights_aligned:", weights_aligned.shape, weights_aligned.names)

weights_aligned: torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')


Functions accepting dimension arguments also take named dimensions:

In [59]:
gray_named = (img_named * weights_aligned).sum('channels')
print(gray_named.shape, gray_named.names)

torch.Size([5, 5]) ('rows', 'columns')


If we want to use tensors outside functions that operate on named tensors, we need to drop the names by renaming them to _None_

In [60]:
gray_plain = gray_named.rename(None)
print("gray_plain:", gray_plain.shape, gray_plain.names)

gray_plain: torch.Size([5, 5]) (None, None)


### Tensor data types
Computations in neural networks are typically executed with **32-bit floating-point** precision. For indexing, PyTorch expects indexing tensors to have a **64-bit integer** data type. So, the most commonly used data types are _float32_ and _int64_.

In order to allocate a tensor of the right numeric type, we can specify the proper _dtype_ as an argument to the constructor:

In [9]:
double_points = torch.ones(5, 2, dtype=torch.double)
print(double_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


También podemos hacer un _cast_ al tipo deseado usando el método correspondiente o empleando el método _to()_

In [11]:
double_points = torch.ones(5, 2).double()
print(double_points)
short_points = double_points.to(dtype=torch.short)
print(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


When mixing data types in operations, the operands are converted to the larger type automatically

In [12]:
points_sum = double_points+short_points
print(points_sum)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], dtype=torch.float64)


### Tensor API
PyTorch offers a lot of operations that we can perform on and between tensors. The vast mayority are available as functions in the _torch_ module ([https://pytorch.org/docs/stable/torch.html](https://pytorch.org/docs/stable/torch.html)) and can also be called as methods of a tensor object.

In [17]:
a = torch.ones(3, 2)
print(a)
a_t = torch.transpose(a, 0, 1)
print(a_t)
a_t2 = a.transpose(0, 1)
print(a_t2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor metadata: storage, size, offset, stride
Values in tensors are allocated in contiguous chunks of memory (one-dimensional array) managed by _torch.Storage_ instances. A _Tensor_ instance is a view of such array that is capable of indexing into that storage using dimension indexes. 

Multiple tensors can index the same storage even if they index into the data differently.

<br>

![](img/storage.png)

<br>

We can have acces to the underlying array using the _storage_ property

In [18]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

We have access to the every single element by indexing the storage array

In [20]:
arr_p = points.storage()
print(arr_p[2])
arr_p[2] = 99.
points.storage()[1] = 66.
print(points)

5.0
tensor([[ 4., 66.],
        [99.,  3.],
        [ 2.,  1.]])


In order to index into a storage, tensors rely on a few pieces of information: size, offset and stride.

<br>

![](img/offset_stride.png)

<br>

The **size** (shape) is a tuple indicating de number of elements in each dimension of the tensor. The **offset**, is the index in the storage corresponding to the first element in the tensor. The **stride** is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension.

For example, accesing an element i, j in a 2D tensor results in accessing:

_storage_\__offset_ + _stride_\[0\]\*i + _stride_\[1\]\*j

This kind of indirection makes some operations inexpensive, like transposing a tensor or extracting a subtensor, because they do not lead to memory reallocations.

In [31]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
print(points)
print("points stride:", points.stride())

second_point = points[1]
print(second_point)
print("second_point size:", second_point.size())
print("second_point offset:", second_point.storage_offset())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
points stride: (2, 1)
tensor([5., 3.])
second_point size: torch.Size([2])
second_point offset: 2


Methods like _transpose_ benefits from this to perform in-place operations without the need of creating a new matrix

In [39]:
m = torch.tensor([[3, 1, 2], [4, 1, 7]])
print(m)
print(m.storage())
print(m.stride())

m_t = m.t()
print(m_t)
print(m_t.storage())
print(m_t.stride())

m_t2 = m.transpose(0,1)
print(m_t2)
print(m_t2.storage())
print(m_t2.stride())

tensor([[3, 1, 2],
        [4, 1, 7]])
 3
 1
 2
 4
 1
 7
[torch.LongStorage of size 6]
(3, 1)
tensor([[3, 4],
        [1, 1],
        [2, 7]])
 3
 1
 2
 4
 1
 7
[torch.LongStorage of size 6]
(1, 3)
tensor([[3, 4],
        [1, 1],
        [2, 7]])
 3
 1
 2
 4
 1
 7
[torch.LongStorage of size 6]
(1, 3)


Some tensor operations in PyTorch only work on contiguous tensors (such as _view_), i.e. a tensor whose values are laid out in the storage from the rightmost dimension onward (for example, in a 2D tensor, the values of each file are contiguous). In such tensors, we can visit each element efficiently without jumping around in the storage.

In the previous example, our initial tensor was contiguous and its transpose was not.


In [41]:
print(m.is_contiguous())
print(m_t.is_contiguous())

True
False


We can create a contiguous tensor from one that is not, but the storage will be reshuffled and the stride will change.

In [51]:
print(m_t)
print(m_t.storage())
print(m_t.is_contiguous())

m_t_cont = m_t.contiguous()
print(m_t_cont)
print(m_t_cont.stride())
print(m_t_cont.storage())
print(m_t_cont.is_contiguous())

tensor([[3, 4],
        [1, 1],
        [2, 7]])
 3
 1
 2
 4
 1
 7
[torch.LongStorage of size 6]
False
tensor([[3, 4],
        [1, 1],
        [2, 7]])
(2, 1)
 3
 4
 1
 1
 2
 7
[torch.LongStorage of size 6]
True


### In-place operations
The _Tensor_ object has a small number of _in place_ operations. They are recognized from a trailing underscore in their name.

Any method without the trainling underscore levaes the source tensor unchanged and instead returns a new tensor

In [21]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Moving tensors to GPU
Currently, pyTorch tensor operations can be improved with the use of CUDA based GPU's (NVIDIA), ROCm based GPU's (AMD) and Google TPU's.

In addition to _dtype_, a PyTorch _Tensor_ has the notion of _device_, which is where on the computer the tensor data is placed.

In [6]:
points_gpu = torch.tensor([[4., 1.], [5., 3.], [2., 1.]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

We could instead copy a tensor created on the CPU onto the GPU

In [7]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In case we have several GPU, we can decide on which GPU we allocate the tensor by passing an index indentifying the correspondant GPU (for example: 'cuda:**0**').

Once we move a tensor onto the GPU, all operations performed on it will be executed by the GPU and the resulting tensors allocated on it. Then, is possible to move our tensors back to the CPU. Instead of the _to_ method, we can use the methods _cuda_ and _cpu_.

In [9]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
points_gpu = points.cuda() # points.cuda(0)
print(points_gpu)
points_cpu = points_gpu.cpu()
print(points_cpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


### NumPy interoperatibility
PyTorch tensors can be converted to NumPy arrays and viceversa very efficiently. It is important to note that, if both objects are onto CPU, then both will share the same data structure

In [26]:
points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)
print(type(points_np), points_np.dtype)

points2 = torch.from_numpy(points_np)
print(points2)
print(type(points2), points2.dtype)

points_np[1][2] = 99
print(points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'> float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'torch.Tensor'> torch.float32
tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1., 99.,  1.],
        [ 1.,  1.,  1.,  1.]])


### Serializing tensors
PyTorch uses **pickle** under the hood to serialized the tensor object, plus dedicated serialization code for the storage.

In [28]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
torch.save(points, 'data/points.t')

Alternative, we can use a file descriptor

In [29]:
with open('data/points.t', 'wb') as f:
    torch.save(points, f)

Loading our points back is similarly a one-liner

In [32]:
points = torch.load('data/points.t')
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Or, equivalently

In [36]:
with open('data/points.t', 'rb') as f:
    points = torch.load(f)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### Serializing to HDF5
In cases where you need interoperatibility with other libraries, you can use the **HDF5** format and library ([www.hdfgroup.org/solutions/hdf5](https://www.hdfgroup.org/solutions/hdf5)). HDF5 is a portable, widely supported format for representing serialized multidimensional arrays, organized in a nested key-value dictionary.

Python supports HDF5 through the _hdf5_ library ([www.h5py.org](https://www.h5py.org)) which accepts and returns data in the form of NumPy arrays

In [38]:
import h5py

points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])

f = h5py.File('data/points.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

Here _coords_ is a **key** into the HDF5 file, associated with the saved data. We can use that key to access the required data in the file, even a indexed slice of it

In [44]:
f = h5py.File('data/points.hdf5', 'r')
dset = f['coords']
last_points = dset[-1:]
print(last_points)
torch_points = torch.from_numpy(dset[-1:])
print(torch_points)
f.close()

[[2. 1.]]
tensor([[2., 1.]])


The data is not loaded when we open the file. The data stays on disk until we request the data (the last row of the matrix in our example). At that point, _h5py_ will return a NumPy array